---
# defaults file for aws-create-ec2
ec2_region: us-east-2

# Instance variables 
ec2_instance_type: t2.micro
ec2_instance_count: 1
ec2_ami_id: ami-0240b09539b9692a0
ec2_volume_size: 30
ec2_keypair_name: Ansible_Created_Keypair

#SG
ec2_security_group: ""

#Instance Tags
ec2_name_tag: Ansible_Created_EC2
ec2_provisioner_tag: Ansible
ec2_created_tag: "{{ ansible_date_time.date }}"

ec2_virtualmachine_ostype: Linux
